apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-v2
  labels:
    app: inventario-app
    version: v2
    rollout: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-app
      version: v2
      rollout: canary
  template:
    metadata:
      labels:
        app: inventario-app
        version: v2
        rollout: canary
    spec:
      containers:
        - name: inventario-app
          image: ghcr.io/kennypallchizaca-coder/inventario-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: APP_VERSION
              value: "v2.0.0-canary"
            - name: APP_COLOR
              value: "green"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: inventario-secret
                  key: API_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
